variables:
  REPO_NAME: recruit2023

stages:
  - setup
  - compile
  - imagebuild
  - deploy

compile_dev:
  image: node:18
  stage: compile
  tags:
    - redrock
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run build
  artifacts:
    expire_in: 3 days
    paths:
      - build
  only:
    - dev/test

compile_prod:
  image: node:18
  stage: compile
  tags:
    - redrock
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run build
  artifacts:
    expire_in: 1 week
    paths:
      - build
  only:
    - master

image_dev:
  stage: imagebuild
  image: reg.redrock.team/base/redrock-helmetci-builder:latest
  tags:
    - redrock
  variables:
    NAMESPACE: fe-dev
  script:
    - "/kaniko/dockerfile-web.sh" 
    - "/kaniko/build-upload --no-ccr" 
  only:
    - dev/test

image_prod:
  stage: imagebuild
  image: reg.redrock.team/base/redrock-helmetci-builder:latest
  tags:
    - redrock
  variables:
    NAMESPACE: fe-prod
  script:
    - "/kaniko/dockerfile-web.sh" 
    - "/kaniko/build-upload"  
  only:
    - master

deploy_dev:
  stage: deploy
  image: reg.redrock.team/base/redrock-helmetci-deployer:latest
  tags:
    - redrock
  variables:
    REDROCK_HELM_CHART: base/local-app
    REDROCK_KUBECONFIG: $REDROCK_LOCAL_KUBECONFIG
    REDROCK_NAMESPACE: fe-dev
  script:
    - deploy
  only:
    - dev/test

deploy_prod:
  stage: deploy
  image: reg.redrock.team/base/redrock-helmetci-deployer:latest
  tags:
    - redrock
  variables:
    REDROCK_HELM_CHART: base/local-app
    REDROCK_KUBECONFIG: $REDROCK_LOCAL_KUBECONFIG
    REDROCK_NAMESPACE: fe-prod
  script:
    - deploy
  only:
    - master
    
deploy_cloud_prod:
  stage: deploy
  image: reg.redrock.team/base/redrock-helmetci-deployer:latest
  tags:
    - redrock
  variables:
    REDROCK_HELM_CHART: base/cloud-app
    REDROCK_KUBECONFIG: $REDROCK_CLOUD_KUBECONFIG
    REDROCK_NAMESPACE: fe-prod
  script:
    - deploy --set "domain=$REDROCK_NAMESPACE.redrock.team"
  only:
    - master
